### ISSUE TITLE
Production errors

### ISSUE THREAD

**Issue by dmarczydlo** [mozilla-frontend-infra/react-lazylog#10]
I have problem with react-lazylog on production. 
When I use UglifyJs I've got:

`ERROR in e5cf7b4c07bad8fabb92.js from UglifyJs
docker_loger    | Unexpected token: name (b) [e5cf7b4c07bad8fabb92.js:130961,1523]`

Also webpack 4.0 and webpack-dev-server": ^3.1.0 have the same problem.

**Comment by eliperelman** [comment]
Unless you are using uglify-es, I don't think you can use the ES2015 version of this. Could you instead import the ES5 version?

```js
import { LazyLog } from 'react-lazylog/lib/LazyLog.es5';
```

**Comment by dmarczydlo** [comment]
Nice. You had absolutely right.
