### ISSUE TITLE
Couldn't find any versions for "react-lazylog" that matches "4.5.3"

### ISSUE THREAD

**Issue by simida0852** [mozilla-frontend-infra/react-lazylog#102]
Hello, I seem to have encountered some problems. Can you help me see it? thank you very much.
I can’t choose the version 4.5.3 in my terminal, but this version has been released on npm.

os: macOS big sur
node: v12.10.0
npm: v6.10.3

![image](https://user-images.githubusercontent.com/12591108/103282244-2116b300-4a10-11eb-93c4-09fd997725e8.png)

**Comment by melloware** [comment]
I have released a 5.0.0 version fork of this project with many new features

GitHub: https://github.com/melloware/react-logviewer

Demo Site: https://melloware.github.io/react-logviewer/
