### ISSUE TITLE
3.1.x - es5 problem

### ISSUE THREAD

**Issue by dmarczydlo** [mozilla-frontend-infra/react-lazylog#11]
After update lazy-logger to version 3.1.1 (from 2.x) the problem `Uncaught TypeError: e is not a function` still exist.

For 2.x `import { LazyLog } from 'react-lazylog/lib/LazyLog.es5';` worked but for 3.1.1 `import {LazyStream, ScrollFollow} from 'react-lazylog/es5';` generating error.

**Comment by eliperelman** [comment]
@dmarczydlo do you have a reduced repo I can try this out on?

**Comment by dmarczydlo** [comment]
Hm... you can use https://github.com/dmarczydlo/docker-logger/tree/greenkeeper/react-lazylog-3.1.3 (branch created by greenkeeper) but before compile you have to update /components/docker/docker.jsx from `import {LazyStream, ScrollFollow} from 'react-lazylog/lib/LazyLog.es5';` to syntax from last version

**Comment by eliperelman** [comment]
@dmarczydlo there are a few other changes in the API which should be documented in the props. I tried out your repo and updated it to this and didn't see any of those ES5 errors, could you try it too?

```jsx
import {LazyLog, ScrollFollow} from 'react-lazylog/es5';

// ...

<ScrollFollow startFollowing render={({follow, onScroll}) => (
  <LazyLog url={URL} follow={follow} onScroll={onScroll} />
)} />
```

**Comment by dmarczydlo** [comment]
Yes but you `LazyLog` instead of `LazyStream`. How can I use `LazyLog` for stream GET? 
And another question can I modify somehow `featchOptions` to send POST request?

**Comment by dmarczydlo** [comment]
I'm not sure that LazyLog working correct.
Look at image below
![screenshot_20180410_073353](https://user-images.githubusercontent.com/26409082/38537973-f782d7be-3c91-11e8-8f7d-acae255f5105.png)

New rows overrides old. LazyLog looks like TextArea also. Can I change it to selecting row (like LazyStream worked)? 

Also last row is still hidden. 

```javascript
fetchOptions={{ method: 'POST' }}  // working correct :)
```

**Comment by eliperelman** [comment]
Wow, that looks really odd, almost like the style isn'y being applied. Can you update to the latest version and see if that fixes anything?

**Comment by dmarczydlo** [comment]
Hm... As I think I using the latest version 
```javascript
"react-lazylog": "^3.1.3",
```

**Comment by dmarczydlo** [comment]
So I think that this issue existing in last version.

**Comment by stephenwilliams** [comment]
I see the same issue with the latest version.

**Comment by eliperelman** [comment]
If you could produce a reduced test repo, that would be really helpful.

**Comment by stephenwilliams** [comment]
I'll get a test repo setup by EoD Monday. Thanks for the work you've done on this project.

**Comment by dmarczydlo** [comment]
@eliperelman  - as I saw you updated project to 2.2.0 version. What does it mean ? Did you reverse some features/props? 

I want to update lazylog to last fine version but I'm confused which version is correct.

**Comment by eliperelman** [comment]
@dmarczydlo apologies, I published #14 but didn't mean for it to be tagged as `latest`. I have re-tagged 3.1.3 as latest.

**Comment by dmarczydlo** [comment]
So 3.1.3 should be latest also should work correctly?  I mean suggested problem in [here](https://github.com/mozilla-frontend-infra/react-lazylog/issues/11#issuecomment-379981120)

**Comment by eliperelman** [comment]
Right, I just don't have any repo to replicate against in order to fix it.

**Comment by dmarczydlo** [comment]
Ok I will check this version on weekend. If this problem will still existing I'll try to create repo for you.

**Comment by stephenwilliams** [comment]
@eliperelman Sorry it took me much longer than I expected to have time to put together an example repo.

Here you go: https://github.com/stephenwilliams/react-lazylog-issue-11

**Comment by eliperelman** [comment]
@dmarczydlo @stephenwilliams I didn't think you would need to do this, but could you manually import the CSS?

```js
import 'react-lazylog/es5/index.css';
```

**Comment by dmarczydlo** [comment]
@stephenwilliams  ```index.css``` not existing in 3.1.3

**Comment by eliperelman** [comment]
I just pushed a patch version, could you try it again?

**Comment by dmarczydlo** [comment]
where is this path? What branch? 
Did you push to npm or only to github somewhere?

**Comment by eliperelman** [comment]
Sorry, it's the latest on npm, 3.1.4.

**Comment by dmarczydlo** [comment]
Hm.. ok this version have index.css. I'm not sure that I understood you but if want to test solution as import ```index.css``` manually - this approach not fix last line issue.

```react-lazylog``` is implemented in https://github.com/dmarczydlo/docker-logger/ master branch was updated to last version 3.1.3 few minutes ago.

**Comment by stephenwilliams** [comment]
@eliperelman Updating to 3.1.4 and adding `import 'react-lazylog/es5/index.css';` fixed it for me

**Comment by dmarczydlo** [comment]
@eliperelman do you working on last line issue?
