### ISSUE TITLE
LazyLog Search Warning

### ISSUE THREAD

**Issue by sberequek** [mozilla-frontend-infra/react-lazylog#117]
Hi,

using the LazyLog component at the first search I get the following message: 

```log
Warning: Failed prop type: The prop `number` is marked as required in `t`, but its value is `undefined`.
```
I don't understand if some parameter is missing in the configuration, but from the examples it doesn't seem to me. Can you help me? here is the LazyLog configuration and the link to an example made with [codesandbox](https://codesandbox.io/s/react-lazylog-search-problem-forked-t7j40?file=/src/App.js). 

```code
<LazyLog height={300} extraLines={1} enableSearch text={log.join("\n")} />
```

Thanks for the support

**Comment by sberequek** [comment]
Hello, any suggestions to solve the problem?

**Comment by melloware** [comment]
It's fixed in my fork:


GitHub: https://github.com/melloware/react-logviewer

Demo Site: https://melloware.github.io/react-logviewer/
