### ISSUE TITLE
Make Links Clickable

### ISSUE THREAD

**Issue by BernhardRode** [mozilla-frontend-infra/react-lazylog#121]
Hi,

backstage.io's scaffolder makes use of this library. We came up with the idea of making links clickable in react-lazylog in https://github.com/backstage/backstage/issues/6841#issuecomment-933594672 

Would this feature be interesting? I'd love to add it to the project.

**Comment by 97amarnathk** [comment]
@BernhardRode This sounds interesting and a low hanging fruit. I can pick this up.

**Comment by BernhardRode** [comment]
It's ready on my machine... although i have to wait until next week (legal clearance,.... corporate stuff)

**Comment by BernhardRode** [comment]
4 weeks later... i'm happy to tell you that i finally got the clearance. So here is the feature.

https://github.com/mozilla-frontend-infra/react-lazylog/pull/123

**Comment by BernhardRode** [comment]
Any chance, getting this merged?

**Comment by melloware** [comment]
@BernhardRode I have forked and published this repo if you want to submit your PR against my repo?

GitHub: https://github.com/melloware/react-logviewer

Demo Site: https://melloware.github.io/react-logviewer/
