### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by JvilleDjango** [mozilla-frontend-infra/react-lazylog#131]
How do you use the loading feature?

I have tried what you see below and a few other options. nothing works? Could you give me some directions? thanks
import { LazyLog, Loading } from "react-lazylog";
`<LazyLog
          extraLines={1}
          enableSearch
          text={logToView ? logToView : "Click on a log to view"}
          caseInsensitive
          loadingComponent={Loading}
        />`
        
  `<LazyLog
          extraLines={1}
          enableSearch
          text={logToView ? logToView : "Click on a log to view"}
          caseInsensitive
          loadingComponent={<Loading/>}
        />`

**Comment by melloware** [comment]
The loading feature is only used I think on the WebSocket streaming variety of the LogViewer?
