### ISSUE TITLE
Demo in docs failing with "NetworkError when attempting to fetch resource." 

### ISSUE THREAD

**Issue by edmorley** [mozilla-frontend-infra/react-lazylog#23]
The readme links to the demo in the docs, however it is currently failing to load (presumably since that Taskcluster log has since been expired):
https://mozilla-frontend-infra.github.io/react-lazylog/

It would be good to switch that to a longer-lived log resource (that's still a long enough log to show off the advantages of react-lazylog).

**Comment by mikeatlas** [comment]
any chance a demo of this can be re-visited?

**Comment by helfi92** [comment]
@mikeatlas I'm not sure I understand. Could you elaborate, please? fwiw, The demo logs are working for me:
* https://mozilla-frontend-infra.github.io/react-lazylog/#lazylog
* https://mozilla-frontend-infra.github.io/react-lazylog/#scrollfollow

**Comment by mikeatlas** [comment]
I'm not sure what I was missing before. Looks great now. Thanks!
