### ISSUE TITLE
Render complete log file after every "n" seconds

### ISSUE THREAD

**Issue by utkarsh447** [mozilla-frontend-infra/react-lazylog#31]
Hi, I have gone through your documentation but i couldn't find a solution which loads contents from log file after every `n seconds` and displays it.

### Scenario
I have a `url` which returns my desired `log file` content and is updating randomly. <br />
I want `react-lazylog` to have a timer which fetches data from the target `url` and updates the log file content after every `n` period of time.

Is there any possible prop or functionality in `react-lazylog` i am missing which targets this situation?

And sorry for creating issue for asking information.

**Comment by helfi92** [comment]
In react, if the `key` prop changes, it will re-render the component. You can have a timer that changes the `key` prop which would subsequently re-fetch data from the target `url`.

**Comment by utkarsh447** [comment]
Thank You, It worked as expected.

**Comment by helfi92** [comment]
You're welcome :)
