### ISSUE TITLE
Is there a way to use this component for local data?  e.g., a list of log messages? 

### ISSUE THREAD

**Issue by brandon-fryslie** [mozilla-frontend-infra/react-lazylog#33]
I would like to use this component to render status/error logs in my application.  The React application will be generating these messages itself based on Websocket messages, errors, or other events.  When there's an error, a message will be added to an array somewhere.

Is there a way I can pass the array to the LazyLog component instead of using a URL?  Is there a similar component I could use that allows passing in an array?

**Comment by helfi92** [comment]
> Is there a way I can pass the array to the LazyLog component instead of using a URL?

Not at the moment, unfortunately. Happy to accept a PR.

**Comment by charlesverge** [comment]
@brandon-fryslie This might be something to start with https://github.com/mozilla-frontend-infra/react-lazylog/pull/37

**Comment by helfi92** [comment]
The latest version of react-lazylog has a `text` prop that allows reading from text instead of a url as well as has the capability to get input from a websocket.
