### ISSUE TITLE
Does FetchOptions work?

### ISSUE THREAD

**Issue by darewreck54** [mozilla-frontend-infra/react-lazylog#55]
From looking at the code, LazyLog has a property called fetchOptions.  I wanted to use it so that I could turn off the compression in the request via Accept-Encoding header.  However, setting the fetchOptions doesn't seem to have any effect.

without any specified fetchOptions, the LazyLog will do a fetch command with the following options:

'accept-encoding: gzip, deflate, br'

which is not what i want.

I did the following:

code:

```
const fetchOptions: RequestInit = {
    headers: {
      'accept-encoding':'indentity',
    }
  }
```
```
  <LazyLog stream url=<url>
        fetchOptions={fetchOptions}
       />
```

After this change, the LazyLog still adds the gzip header option and ignored the fetch options.

Thanks,
Derek

**Comment by aca** [comment]
Experienced the same. Any updates?

**Comment by helfi92** [comment]
It should work. If it doesn't, do you mind creating a [codesandbox
