### ISSUE TITLE
Question about LogViewer and breaking it into columns?

### ISSUE THREAD

**Issue by darewreck54** [mozilla-frontend-infra/react-lazylog#56]
This is more of a question than anything.  I have a file with timestamps that match line to line with the log files.  Is it possible to break the log viewer into two columns one of the time stamps and the other for the content.  Then the user can toggle the timestamp.  

Thanks,
Derek

**Comment by helfi92** [comment]
I would say that would be possible once we allow feeding text instead of a url to the logviewer. You would be able to do any kind of pre-processing prior to feeding the text to the log viewer.

**Comment by helfi92** [comment]
The latest version of react-lazylog allows feeding text via the `text` prop which should allow pre-processing the data before feeding it to the component.
