### ISSUE TITLE
ANSI escape codes not parsed correctly

### ISSUE THREAD

**Issue by timdudman** [mozilla-frontend-infra/react-lazylog#57]
When colouring log text with ANSI escape codes, react-lazylog displays the escape code instead of parsing it.

A simple example of an ANSI-escaped log can be found here: https://gist.githubusercontent.com/timdudman/b84de8147a6d7301554ec22a9993c8b8/raw/bfb35ead64dba8788b5d7f609f9ee1e0cd6f377a/ansi.log

```
Oct 10, 2019 07:22:57 \x1b[34mINFO:\x1b[0m Some text
Oct 10, 2019 07:22:58 \x1b[34mINFO:\x1b[0m Some more text
```

**INFO** should be coloured blue, and **WARNING** should be coloured red. Passing these lines to src/ansiparse.js directly results in the correct behaviour:

```
import ansiparse from './ansiparse.js'
import { decode } from './encoding.js';
import str2ab from 'string-to-arraybuffer';

ansiparse(decode(str2ab("Oct 10, 2019 07:22:57 \x1b[34mINFO:\x1b[0m Some text")))
```

![image](https://user-images.githubusercontent.com/14940862/66732540-48598280-ee54-11e9-87e9-be655d42a720.png)

Within react-lazylog 4.3.2 however, the ANSI codes are passed to src/ansiparse.js with an additional escape, i.e.  **\\\x1b[34mINFO:\\\x1b** instead of **\x1b[34mINFO:\x1b** (thanks for investigating @helfi92):

```
import React from 'react';
import { render } from 'react-dom';
import { LazyLog } from 'react-lazylog';

render((
  <LazyLog url="https://gist.githubusercontent.com/timdudman/b84de8147a6d7301554ec22a9993c8b8/raw/bfb35ead64dba8788b5d7f609f9ee1e0cd6f377a/ansi.log" />
), document.getElementById('root'));
```

![image](https://user-images.githubusercontent.com/14940862/66733179-9f605700-ee56-11e9-8d8c-f62e0f4872da.png)

**Comment by timdudman** [comment]
Looks like this was an issue encoding ANSI codes from Java.

**Comment by helfi92** [comment]
@timdudman Works now?

**Comment by timdudman** [comment]
Yes - **\x1b** is the Javascript encoding for escape. The log was served from Java so needed **(char)27** encoded in the string as the escape sequence. When I debugged I didn't see the double **\** you mentioned seeing, but the problem has been fixed by changing the Java code that decorates the log before serving it.

**Comment by helfi92** [comment]
Ah, awesome. Thanks for the update!

**Comment by YevhenTarashchyk** [comment]
@helfi92 or @timdudman Could you pls tell me why it doesn't work for instance with 107mERROR  ...from ansi table in should be red colored, but it doesn't work for me
