### ISSUE TITLE
text prop adds instead of replace

### ISSUE THREAD

**Issue by frankforpresident** [mozilla-frontend-infra/react-lazylog#68]
I've made a view to display logging on a page from multiple pages. LazyLog is exactly what I need except it appends data instead of replacing it when provided as text.
 Useage:
`<LazyLog extraLines={0} enableSearch text={logging} caseInsensitive follow={follow} />`

Currently I'm in control of the data that is provided to my components. Since it is possible to view multiple logging files, the data needs to change. Is there a "reset" property that will reset the previous logging?

**Comment by frankforpresident** [comment]
I found a workaround for this issue but it will break the ability to search.

`
 const Logger = () => <LazyLog extraLines={0} enableSearch text={logging} caseInsensitive follow={follow} />;
  return (
    <div id="logViewContainer" className={styles.content}>
      <Logger />
    </div>
  );
`

**Comment by helfi92** [comment]
👋

The LazyLog component should render whatever you give it in `text`. Are you saying that when `text` changes, it is appending instead of replace the full text? If this is the case, then that's probably a bug.

**Comment by frankforpresident** [comment]
@helfi92 

Is this issue fixed with 4.5.1?

**Comment by helfi92** [comment]
I wasn't able to reproduce the error using https://mozilla-frontend-infra.github.io/react-lazylog/#lazylog under the "Log viewing using text from a string :" section. Happy to re-open if this is still an issue. Any chance you could provide a codepen example for me to reproduce this issue?

**Comment by frankforpresident** [comment]
> I wasn't able to reproduce the error using https://mozilla-frontend-infra.github.io/react-lazylog/#lazylog under the "Log viewing using text from a string :" section. Happy to re-open if this is still an issue. Any chance you could provide a codepen example for me to reproduce this issue?

Sure, will do this next week

**Comment by helfi92** [comment]
Sounds good, thanks!

**Comment by liorbd** [comment]
Hey @helfi92. I've also encountered this issue. When i update the `text` prop, the new value appended to the previous one.
There is a codesandbox with small example:
https://codesandbox.io/s/react-lazylog-yd22x.
If it's a Bug, can you please re open this issue?

**Comment by helfi92** [comment]
Thanks for setting up the demo. I can replicate. This is a bug.

**Comment by helfi92** [comment]
@liorbd Does https://github.com/mozilla-frontend-infra/react-lazylog/pull/74 look good to you?

**Comment by liorbd** [comment]
@helfi92 i would do something like: 
https://github.com/mozilla-frontend-infra/react-lazylog/pull/75/files
To enable replacing the line from other places.
Thanks!

**Comment by helfi92** [comment]
Fixed in react-lazylog@4.5.2. Thank you @liorbd 💯
