### ISSUE TITLE
Word wrapping

### ISSUE THREAD

**Issue by ffMathy** [mozilla-frontend-infra/react-lazylog#71]
Word-wrapping of lines would be super nice.

**Comment by helfi92** [comment]
I think adding this feature would make it hard to jump to a specific line now that each line does not have a fixed height but I could be wrong. PRs are welcome :)

**Comment by ffMathy** [comment]
I'm willing to sacrifice that functionality for this feature.

I just want to display logs, not be able to search or jump around.

**Comment by helfi92** [comment]
Fair enough. We should make this explicit in the docs when adding this feature so that users are aware of this.
