### ISSUE TITLE
How do you add line click listener?

### ISSUE THREAD

**Issue by bingle87** [mozilla-frontend-infra/react-lazylog#72]
I am using LazyLog as follows:

`<LazyLog 
                    enableSearch 
                    selectableLines
                    caseInsensitive 
                    url={this.props.url}
                    scrollToLine={Number(this.props.lineNumber)+5}
                    highlight={Number(this.props.lineNumber)}
                    onClick={() => {debugger}}
                >
                    <Line onRowClick={() => {debugger}} />
                    <LineNumber onClick={() => {debugger}} />
                </LazyLog>`

I cant get anything to trigger. What am I doing wrong?

**Comment by liorbd** [comment]
@bingle87 Currently you cannot provide `onRowClick` to the `<LazyLog />` component, And also cannot provide children to it.
@helfi92 what do you think about adding `onRowClick` prop?
I'll be happy to open PR for that.

**Comment by helfi92** [comment]
Could you use the `onHighlight` prop that we expose on the LazyLog component to do what you are trying to do?
