### ISSUE TITLE
Keep only latest 1000 lines

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [mozilla-frontend-infra/react-lazylog#76]
I am using LazyLog with websocket.

**Current Behavior**:  All the messages are retained. 

Please let me know how to keep only latest 1000 lines.

Any references/samples will be helpful.

**Comment by helfi92** [comment]
This is not currently supported. What is your use case for that?

**Comment by saichaitanyaeruvaram** [comment]
**Environment:** NodeJs Server and ReactJs Client

After client connects with server, server constantly sends log messages via websocket.

**Client can be open forever in my case** 
I've observed the client tab memory keeps increasing overtime  (> 1 GB) and after some point > 20k lines, lazylog view becomes stuck and recovers after few seconds

For my use case, I just need to retain latest 1000 (configurable) messages.

**Comment by helfi92** [comment]
> I've observed the client tab memory keeps increasing overtime (> 1 GB) and after some point > 20k lines, lazylog view often becomes stuck and recovers after few seconds

That would be considered a bug which should get fixed. The log viewer is virtualized so only what is currently on the screen is loaded. Anything above/under the viewable screen should not be loaded in the DOM. If you can create a code sandbox (similar to https://github.com/mozilla-frontend-infra/react-lazylog/issues/68#issuecomment-602170094) then it would be easy to look into it. Thanks!

**Comment by saichaitanyaeruvaram** [comment]
https://codesandbox.io/s/react-lazylog-jtl73?file=/src/App.js

<img width="1920" alt="lazylog_taskmanager" src="https://user-images.githubusercontent.com/10721851/82575100-a34f1700-9ba5-11ea-8a7d-36af5f4c8a08.png">
