### ISSUE TITLE
yarn command failed

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [mozilla-frontend-infra/react-lazylog#77]
<img width="1153" alt="lazylog" src="https://user-images.githubusercontent.com/10721851/82530582-4464b000-9b5b-11ea-9721-92910d74eb33.PNG">

OS: Windows 10
NodjeJs: 12.14
NPM: 6.13.4
Yarn: 1.22.4

Kindly let me know any dependencies/versions.

**Comment by helfi92** [comment]
I've never seen this error. I am running macOS so perhaps this is windows specific. Could you try removing your node_modules directory and trying again to see if that fixes it?

```
rm -rf node_modules
yarn
```

**Comment by saichaitanyaeruvaram** [comment]
It a fresh clone of the repo.
Removed the node_modules directory and still the same error.
