### ISSUE TITLE
Is there a way to add objects to the search bar?

### ISSUE THREAD

**Issue by camd** [mozilla-frontend-infra/react-lazylog#78]
I'll like to be able to add some `HTML` to the search bar to add a few buttons.  Since there's lots of screen real-estate on the left side, this would be handy placement.

Perhaps via `children`?

**Comment by helfi92** [comment]
Hey @camd. There isn't a well defined way to do this right now. In firefoxci, we add a couple buttons via css with position `absolute`. https://firefox-ci-tc.services.mozilla.com/tasks/dKSj47r1QGmIKZJJyFjEIQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FdKSj47r1QGmIKZJJyFjEIQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log.

If this is not good enough for your use case, we can try to see how we can add this functionality to this library.

**Comment by slumbering** [comment]
> Hey @camd. There isn't a well defined way to do this right now. In firefoxci, we add a couple buttons via css with position `absolute`. https://firefox-ci-tc.services.mozilla.com/tasks/dKSj47r1QGmIKZJJyFjEIQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FdKSj47r1QGmIKZJJyFjEIQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log.
> 
> If this is not good enough for your use case, we can try to see how we can add this functionality to this library.

This functionality would be very appreciated :). 

Many thanks for the work you've done
