### ISSUE TITLE
last row not displaying & follow not working

### ISSUE THREAD

**Issue by dmarczydlo** [mozilla-frontend-infra/react-lazylog#8]
I using react-lazylog into my project. To get data I using LazyStream. The problem is that last row is not displaying. 

As I Investigated you using `position: absolute` for it. Last row has incorrect `top` attribute for position absolute.

Second problem is property `follow` - it's not working.

My code: 
`<ScrollFollow startFollowing>
                    {({follow, onScroll}) => (
                        <LazyStream url={URL} follow={follow} onScroll={onScroll} />
                    )}
                </ScrollFollow>`

**Comment by eliperelman** [comment]
I have refactored the codebase, and this may now be resolved. I have deployed an interactive styleguide, with a streaming/scrolling demo. You could put your URL in the demo by clicking "VIEW CODE" and pasting it there, and see if it works, and let me know if this still happens there?

https://mozilla-rpweb.github.io/react-lazylog/#scrollfollow

**Comment by dmarczydlo** [comment]
Still the same issue

**Comment by dmarczydlo** [comment]
@eliperelman any update for last row issue?

**Comment by eliperelman** [comment]
There is a fix in the v2 release line, but it has not been ported to v3/master.

https://github.com/mozilla-frontend-infra/react-lazylog/commit/0d5df76cb50f75ab8c1940cf4b21e61fe932c7f5

Would you be interested in opening a PR with this?

**Comment by dmarczydlo** [comment]
Hm.. sound's good. Yeah PR should be opened but I'm little confused. Which one is the latest? (I mean version)

**Comment by logvi** [comment]
any news about fixing it?

**Comment by helfi92** [comment]
Regarding "last row not displaying", this was fixed a while ago. You can use the [`extraLines`](https://mozilla-frontend-infra.github.io/react-lazylog/#lazylog) prop.

```
<LazyLog extraLines={1} ... />
```

Regarding "follow not working", this should also be working. See the demo for an example.
