### ISSUE TITLE
[BUG] Search bar searches within the log even when it is empty

### ISSUE THREAD

**Issue by SuyashSalampuria** [mozilla-frontend-infra/react-lazylog#81]
Even when there is no text present in the search bar, it searches within the log. And if the filter button(those four horizontal lines) is  active, it does not show any log with message ```No filter results```. In my opinion, search should not be performed when the searchbar is empty

**Comment by helfi92** [comment]
> Even when there is no text present in the search bar, it searches within the log

It will only search if the filter is active. By default, the search is not set. You can see this in the demo component in https://mozilla-frontend-infra.github.io/react-lazylog/#lazylog.

**Comment by helfi92** [comment]
If the search is triggered only on an empty log then that would be a bug.

**Comment by SuyashSalampuria** [comment]
Oh!
I got that @helfi92 
Also, I notice that any  formatting done using formatPart props is log is removed when the search filter is done
Is that a bug or some expected behaviour @helfi92 
If I want to do that formatting in my code when search is  performed
How is it possible

**Comment by helfi92** [comment]
@SuyashSalampuria I'm not sure I understand. Do you have steps I can do to reproduce your issue?

**Comment by SuyashSalampuria** [comment]
I have added a new issue for it @helfi92 
I have added colors based on conditions to each log line to log. On searching anything from the searchbar, these colors are lost and are restored when the search text is removed
I don't expect the colors to be lost
Could you please answer it at any place

For reproducing it
Add colors to the individual log-lines  using formatPart(prop)
Now type something from the search bar and you will notice that colors are gone
