### ISSUE TITLE
What is the simplest way to enable word wrap?

### ISSUE THREAD

**Issue by arch-DJ** [mozilla-frontend-infra/react-lazylog#83]
I would like to enable word wrap so that there is no need to do horizontal scrolling. 
I tried to add css class to **lineClassName** with **word-wrap** property set to **break-word**.
Unfortunately, this did not work.

**Comment by helfi92** [comment]
Hey. We make sure every row has a fixed height to allow us to have the feature of jumping to line numbers. Allowing word wrapping would, i think, make it hard to do.

**Comment by panniyuyu** [comment]
I think it is necessary and hope to support.😁

**Comment by StevenMassaro** [comment]
I switched over to using PatternFly's logviewer, which supports line wrapping by default: https://www.patternfly.org/v4/extensions/log-viewer
