### ISSUE TITLE
Debounce on search input?

### ISSUE THREAD

**Issue by fzxt** [mozilla-frontend-infra/react-lazylog#86]
Unless I'm missing something, it seems like right now it's searching on every keystroke:

https://github.com/mozilla-frontend-infra/react-lazylog/blob/master/src/components/SearchBar/index.jsx#L60-L63

Any chance we could expose an option to debounce user input on the search bar? I.e., only search until after the user has stopped typing?

**Comment by helfi92** [comment]
The current implementation will start searching once the user has typed 2 characters.

https://github.com/mozilla-frontend-infra/react-lazylog/blob/962d294b18dd657a0c84ab05062a6bd8339c8180/src/components/LazyLog/index.jsx#L483-L485

Adding an optional debounce option makes sense to me. PRs are welcome.

**Comment by fzxt** [comment]
i'll try taking this on -- thanks!
