### ISSUE TITLE
How to use react-lazylog with babel-7/corejs-3 + TypeScript?

### ISSUE THREAD

**Issue by jfoliveira** [mozilla-frontend-infra/react-lazylog#89]
Hi,

Any advice on how to use `react-lazylog` in projects with `babel@7` and `core-js@3`?

After a day spent on some research, I found out that the root cause seems to be this issue in the `react-virtualized` repository:
https://github.com/bvaughn/react-virtualized/issues/1373 
I tried many (if not all of) the workarounds suggested in the above issue with no luck.

I'm trying to get started using `react-lazylog` and add it to an existing large React app that uses `parcel` + `babel 7` for bundling, and it seems `react-lazylog` can't be rendered with this setup - it seems it has a conflict with `corejs-3` (which is the stable and recommended version of core-js).

Any suggestions?

**Steps to reproduce:**
- create a new app with `create react app --typescript`
- add `parcel`(tried with parcel 1 and parcel 2) as a dev dependency
- add `react-lazylog` as a dependency
- add `start`, `build` and `serve` scripts to `package.json`:
```json
  "scripts": {
    "start": "tsc --noEmit && parcel public/index.html -p 5000 --dist-dir build --open",
    "build": "NODE_ENV=production parcel build public/index.html --dist-dir build",
    "serve": "serve -s ./build -l 5000",
```
- run `yarn build && yarn serve`

**Warning at build time:**
```shell
$ yarn build && yarn serve
yarn run v1.22.4
$ NODE_ENV=production parcel build public/index.html -d build
⚠️  Could not load existing sourcemap of "../node_modules/react-lazylog/build/index.js".
```
**Error message at runtime - browser console:**
```
require(...).Object is undefined
```

**Comment by helfi92** [comment]
Interesting. It looks like the issue surfaces when corejs-3 is installed. A temporary fix might be to install a v2 version of `core-js` until the issue is fixed upstream.

**Comment by jfoliveira** [comment]
Just a quick update, in case it helps others:
- after upgrading [parceljs](https://v2.parceljs.org/) to version `"^2.0.0-nightly.462"` the issue is gone 

Kudos to the `parceljs` team!

`react-lazylog` is now working like a charm.
Thank you for this amazing package folks!

**Comment by jfoliveira** [comment]
Thanks @helfi92 for your help! Closing this issue, as it's been resolved.

Waiting for updates on #114 to decide if we keep using `react-lazylog` or not.

**Comment by melloware** [comment]
@jfoliveira i would switch to my fork.  Most people have moved over there.  This project no commits in 3+ years.  It is typscript native and it has merged most of the open PR's that were useful from this fork as well as new users have already added WebSocket improvements and others.
