### ISSUE TITLE
[BUG] error uncaught error: invalid offset NaN specified

### ISSUE THREAD

**Issue by x0152** [mozilla-frontend-infra/react-lazylog#93]
Hi
I've noticed strange behavior. If lazylog's parent container have style <code>height: 100%</code> and doesn't have other elements then It will fail with error: error uncaught error: 
invalid offset NaN specified

Example: 
```HTML
<div style={{"height":"100%"}}>
      <LazyLog text='Hello' />
</div >
```

![image](https://user-images.githubusercontent.com/45021974/92411744-cbad5200-f151-11ea-9ef7-2553119a7319.png)
https://github.com/tiburon-security/jupyterlab_scheduler/issues/6

**Comment by timjonesdev** [comment]
I'm also seeing this error, and I haven't been able to get it to work even setting the container height to a static value. It was working previously, and I've tried different versions of both lazy log and react-virtualized to see if I can pinpoint when it's introduced. Any additional insight or help from the maintainers would be greatly appreciated.

**Comment by timjonesdev** [comment]
I saw this error as well, and I found that it was a problem with my data feed. So, again, user error.

**Comment by fabdrol** [comment]
I had this issue as well. More information:

**Works:**
```jsx
<Layout.Content className='logs logs--content'>
  <div>Last update: <strong>{moment().diff(logs.lastReceived, 'seconds')}s ago</strong></div>
  <div className='logs logs--logviewer-container'>
    <LazyLog enableSearch={true} extraLines={1} caseInsensitive={true} text={lines} />
  </div>
</Layout.Content>
```

**Does not work:**
```jsx
<Layout.Content className='logs logs--content'>
  <div className='logs logs--logviewer-timestamp'>Last update: <strong>{moment().diff(logs.lastReceived, 'seconds')}s ago</strong></div>
  <div className='logs logs--logviewer-container'>
    <LazyLog enableSearch={true} extraLines={1} caseInsensitive={true} text={lines} />
  </div>
</Layout.Content>
```

The **only** difference is that in the 2nd snippet, the adjacent `div` has styling.

**Comment by fabdrol** [comment]
Actually; that may not be it. When reloading the "working" solution consecutively, it sometimes works, sometimes doesn't

**Comment by SilkageNet** [comment]
> Actually; that may not be it. When reloading the "working" solution consecutively, it sometimes works, sometimes doesn't

This error occurs if `lines` is empty.
